# -*- coding: utf-8 -*-
"""ResearchAssist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eay_odN8bOEotp8eBBmgJRiTZLSo-GT
"""

!pip install langchain==0.0.284
!pip install python-dotenv==1.0.0
!pip install streamlit==1.22.0
!pip install unstructured==0.9.2
!pip install tiktoken==0.4.0
!pip install faiss-cpu==1.7.4
!pip install libmagic==1.0
!pip install python-magic==0.4.27
!pip install python-magic-bin==0.4.14
!pip install openai==0.28.0

# Commented out IPython magic to ensure Python compatibility.
# %pip install "accelerate>=0.16.0,<1" "transformers[torch]>=4.28.1,<5" "torch>=1.13.1,<2"

import os
import streamlit as st
import pickle
import time
import langchain
from langchain import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.chains.qa_with_sources.loading import load_qa_with_sources_chain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader

"""**1)LOAD DATA**"""

loaders = UnstructuredURLLoader(urls=[
    "https://www.sumobrain.com/patents/wipo/Rational-identification-fda-approved-drugs/WO2022043816A2.html"
])
data = loaders.load()
len(data)

"""**2)SPLIT THE DATA INTO CHUNKS**"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

# As data is of type documents we can directly use split_documents over split_text in order to get the chunks.
docs = text_splitter.split_documents(data)

len(docs)

docs[0].page_content

documents = [doc.page_content for doc in docs]

"""**3)INSERTING MODEL**"""

import torch
from transformers import pipeline

generate_text = pipeline(model="databricks/dolly-v2-3b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")
res = generate_text("Explain to me the difference between nuclear fission and fusion.")
print(res[0]["generated_text"])



"""**4)CREATING EMBEDDINGS**"""

!pip install sentence_transformers
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
embeddings = model.encode(sentences)
print(embeddings)

"""**5)STORING INTO VECTOR DATABASE**"""

import pickle
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import pandas as pd


class VectorStore:
    def __init__(self, chunks: list[str], embeddings_path: str = 'embeddings.pkl', model=None,
                 N: int = 5, metric: str = 'cosine'):
        print('vector store initializing ...')
        self._path: str = embeddings_path
        self._model=model
        self._embeddings: list[dict] or None = (
            self._embed_texts(chunks, False) if model is not None
            else self._load()
            )
        self._metric = metric
        self._n = N

    def get_path(self) -> str:
        return self._path

    def get_embeddings(self) -> list[dict]:
        return self._embeddings

    def _load(self) -> list[list[float]]:
        try:
            return pickle.load(self.get_path())

        except Exception as e:
            print(e)
            print('something went wrong while loading embeddings')
            return []

    def _embed_texts(self, texts: list[str],
                     is_question: bool = False) -> list[dict]:
        try:
            _embeddings = self._model.encode(texts)
            print('embeddings created successfully..')

            if not is_question:
                embeddings: list[dict] = [
                    {'text': txt, 'embeddings': embedding}
                    for txt, embedding in zip(texts, _embeddings.tolist())
                    ]
                self._dump_embeddings(embeddings)

            else:
                embeddings = _embeddings.tolist()

            return embeddings

        except Exception as e:
            print(e)
            print('something went wrong while embedding the texts')
            return []

    @staticmethod
    def _dump_embeddings(embeddings):
        try:
            pickle.dump(embeddings, open('embeddings.pkl', 'wb'))
            print('embeddings stored successfully.')

        except Exception as e:
            print(e)
            print('something went wrong while writing embeddings...')

    def _get_top_n_chunks_cosine(self, question_embeddings: list[float]) -> list[str]:
        top_n_chunks: list[dict] = []
        print(f'fetching top {self._n} relevant paragraphs')

        try:
            for chunk in tqdm(self._embeddings):
                chunk_text: str = chunk.get('text')
                chunk_embeddings: list[float] = chunk.get('embeddings')
                _score = cosine_similarity([chunk_embeddings,
                                                   question_embeddings])
                top_n_chunks.append({
                    'text': chunk_text,
                    'score': _score[0][1]
                })

            _chunks: list[str] = pd.DataFrame(top_n_chunks).sort_values(by='score', ascending=False)['text'].to_list()
            return _chunks[:self._n] if self._n <= len(_chunks) else _chunks

        except Exception as e:
            print(e)
            print('something went wrong while fetching the top paragraphs based on cosine similarity')

    def _get_top_n_chunks(self, question_embeddings: list[float]) -> list[str]:
        if self._metric == 'cosine':
            return self._get_top_n_chunks_cosine(question_embeddings)

        else:
            print(f'invalid metric {self._metric}')
            return []

    def get_relevant_chunks(self, question: str) -> list[str]:
        question_embeddings = self._embed_texts(texts=[question],
                                                is_question=True)
        question_embeddings = question_embeddings[0] if isinstance(question_embeddings, list) and isinstance(question_embeddings[0], list) and question_embeddings[0] else []

        if question_embeddings:
            return self._get_top_n_chunks(question_embeddings)
        else:
            print('something went wrong while fetching embeddings of the question.')
            return []


vs = VectorStore(documents, 'embeddings.pkl', SentenceTransformer('sentence-transformers/all-mpnet-base-v2'))
question="identify repurposed drug for covid 19"
relevant_chunks = vs.get_relevant_chunks(question)
print(relevant_chunks)

"""**6)FETCHING RELEVANT CHUNKS**"""

print(relevant_chunks)

len(relevant_chunks)

chunks_text = '\n\n'.join(relevant_chunks)

"""**7)QUESTION AND ANSWER PROMPT**"""

qna_prompt='''# OBJECTIVE #
To answer a given "Question" based ON ONLY THE "Reference Material" provided in an informative and precise manner. Don't assume anything, in case the "Reference Material" are not helpful in answering the "Question", ask for further details from the user.

>>

# Reference Material #
{CHUNKS}

>>

# INSTRUCTIONS #
- When you feel the Reference Material have content related to the question, generate the answer like how a Chatbot would respond to the question. This is to ensure the user feels they are interacting with another human.
>>

# Question #
{QUESTION}'''.replace('{CHUNKS}',chunks_text).replace('{QUESTION}',question)

print(qna_prompt)

"""**8)OUTPUT**"""

print(generate_text(qna_prompt))